DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'lore') THEN
        CREATE ROLE lore LOGIN PASSWORD 'lore' NOSUPERUSER NOCREATEDB NOCREATEROLE;
    END IF;
END $$;

ALTER DATABASE lore OWNER TO lore;
ALTER SCHEMA public OWNER TO lore;
GRANT ALL PRIVILEGES ON DATABASE lore TO lore;
GRANT CREATE, USAGE ON SCHEMA public TO lore;
